//  TODO 后台管理
import {Dashboard} from "../../layout";
import {DashBoardHome} from "../../views";



export default [
  {
    path:'/dashboard',
    name:'dashboard',
    component:Dashboard,
    redirect:'/dashboard',
    children:[
      {
        path:'',
        name:'dashboardHome',
        component:DashBoardHome,
        meta:{title:"后台管理首页"}
      }
    ]
  },
  {
    path:'/settings',
    name:'settings',
    component:Dashboard,
    redirect:'/settings',
    meta:{title:"系统设置"},
    children:[
      {
        path:'menu',
        name:'settingsMenu',
        component:()=>import('@/views/dashboard/Setting/Menu'),
        meta:{title:'菜单管理'}
      },
      {
        path:'role',
        name:'settingsRole',
        component:()=>import('@/views/dashboard/Setting/Role'),
        meta:{title:'权限管理'}
      }
    ]
  },
  {
    path:'/user',
    name:'user',
    component:Dashboard,
    redirect:'/user',
    meta:{title:"用户管理"},
    children:[
      {
        path:'',
        name:'userList',
        component:()=>import('@/views/dashboard/Users'),
        meta:{title:"用户列表"}
      },
      {
        path:'admin',
        name:'userAdmin',
        component:()=>import('@/views/dashboard/Users'),
        meta:{title:"管理员列表",role:1}
      }
    ]
  },
  {
    path:'/resource',
    name:'resource',
    component:Dashboard,
    redirect:'/resource/data',
    meta:{title:"资源管理"},
    children:[
      {
        path:'data',
        name:'resourceData',
        component:()=>import('@/views/dashboard/Resource/Data'),
        meta:{title:"数据资源"}
      }, {
        path:'from',
        name:'resourceFrom',
        component:()=>import('@/views/dashboard/Resource/From'),
        meta:{title:"资源来源"}
      }, {
        path:'dynamic',
        name:'resourceDynamic',
        component:()=>import('@/views/dashboard/Resource/Dynamic'),
        meta:{title:"数据动态"}
      }, {
        path:'set',
        name:'resourceSet',
        component:()=>import('@/views/dashboard/Resource/Set'),
        meta:{title:"数据集"}
      },{
        path:'label',
        name:'resourceLabel',
        component:()=>import('@/views/dashboard/Resource/Label'),
        meta:{title:"标签"}
      },
    ]
  },
  {
    path:'/interface',
    name:'interface',
    component:Dashboard,
    redirect:'/interface/local',
    meta:{title:"接口管理"},
    children:[
      {
        path:'local',
        name:'interfaceLocal',
        component:()=>import('@/views/dashboard/Interface/Local'),
        meta:{title:"本地接口"}
      },
      {
        path:'out',
        name:'interfaceOut',
        component:()=>import('@/views/dashboard/Interface/Out'),
        meta:{title:"外部接口"}
      },
    ]
  },
  {
    path:'/dataShopping',
    name:"dataShopping",
    component:Dashboard,
    redirect:'/dataShopping/nav',
    meta:{title:'数据超市'},
    children:[
      {
        path:'nav',
        name:'dataShoppingNav',
        component:()=>import('@/views/dashboard/DataShopping/Nav'),
        meta:{title:"左侧导航"}
      },
      {
        path:"approval",
        name:"dataShoppingApproval",
        component:()=>import('@/views/dashboard/DataShopping/Approval'),
        meta:{title:"接口审批"}
      }
    ]
  },
  {
    path:'/task',
    name:"task",
    component:Dashboard,
    redirect:'/task',
    meta:{title:'任务管理'},
    children:[
      {
        path:'',
        name:'taskIndex',
        component:()=>import('@/views/dashboard/Task'),
        meta:{title:"任务列表"}
      }
    ]
  },
  {
    path:'/settlementM',
    name:'settlementM',
    component:Dashboard,
    redirect:'/settlementM/apply',
    meta:{title:"入驻管理"},
    children:[
      {
        path:'apply',
        name:'settlementMApply',
        component:()=>import("@/views/dashboard/settlementM/Apply"),
        meta:{title:"入驻审批"}
      }
    ]
  },
  {path:'*',redirect:'/dashboard'}
]
